const dialog=document.querySelector('#menu-dialog'),menu=document.querySelector('#menu');let lang='uk';
menu.onclick=()=>{dialog.showModal();menu.setAttribute('aria-expanded','true');labels()};document.querySelector('#close-menu').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{menu.setAttribute('aria-expanded','false');menu.focus();labels()});dialog.querySelectorAll('a').forEach(a=>a.onclick=()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const bilingual=[...document.querySelectorAll('[data-en]')];bilingual.forEach(e=>e.dataset.uk=e.textContent);
function labels(){const en=lang==='en';menu.setAttribute('aria-label',dialog.open?(en?'Close menu':'Закрити меню'):(en?'Open menu':'Відкрити меню'));document.querySelector('#close-menu').setAttribute('aria-label',en?'Close menu':'Закрити меню');dialog.setAttribute('aria-label',en?'Navigation':'Навігація');document.querySelector('.language').setAttribute('aria-label',en?'Language':'Мова');document.querySelectorAll('[data-home]').forEach(a=>a.href=new URL('../?lang='+lang,location.href).href);document.querySelectorAll('[data-site-link]').forEach(a=>{const u=new URL(a.href);u.searchParams.set('lang',lang);a.href=u.href})}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;document.documentElement.lang=lang;bilingual.forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll('[data-lang]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.lang===lang)));document.title=lang==='en'?'IFTORA — Competencies':'IFTORA — Компетенції';const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);labels()});
if(new URLSearchParams(location.search).get('lang')==='en')document.querySelector('[data-lang=en]').click();labels();
const reduced=matchMedia('(prefers-reduced-motion:reduce)');const blocks=[...document.querySelectorAll('.cap-block')];const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.16});if(!reduced.matches)blocks.forEach(e=>{e.classList.add('motion-ready');observer.observe(e)});reduced.addEventListener('change',()=>{if(reduced.matches){observer.disconnect();blocks.forEach(e=>e.classList.add('is-visible'))}});

function contactLinks(){const language=document.documentElement.lang;document.querySelectorAll('[data-contact-form]').forEach(a=>a.href='../contacts/?lang='+language+'#request-form');document.querySelectorAll('[data-contact-page]').forEach(a=>a.href='../contacts/?lang='+language)}contactLinks();document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',contactLinks));
