(()=>{
const $=s=>document.querySelector(s),form=$('#inquiry-form'),list=$('#direction-options'),trigger=$('#direction'),options=[...list.querySelectorAll('[role=option]')],touched=new Set();let file=null,fileIssue='',state='',sending=false,active=0;
const dict={uk:{placeholder:'Оберіть напрям',submit:'Надіслати запит',sending:'Надсилаємо запит…',success:'Дякуємо, запит надіслано',error:'Не вдалося надіслати запит. Спробуйте ще раз або напишіть нам на email',unconfigured:'Відправлення у прев’ю ще не підключене. Дані не надіслано — напишіть нам на info@iftora.com',name:'Вкажіть ім’я — щонайменше 2 символи',email:'Вкажіть коректний email',direction:'Оберіть напрям запиту',description:'Опишіть задачу — від 10 до 5000 символів',format:'Цей формат файла не підтримується',size:'Розмір файла має бути не більше 10 МБ',empty:'Порожній файл не можна додати',file:'Файл',remove:'Видалити файл',required:'Обов’язкове поле'},en:{placeholder:'Select an inquiry area',submit:'Send an inquiry',sending:'Sending your inquiry…',success:'Thank you, your inquiry has been sent',error:'Unable to send your inquiry. Please try again or email us',unconfigured:'Submission is not connected in this preview. No data was sent — please email info@iftora.com',name:'Enter a name with at least 2 characters',email:'Enter a valid email address',direction:'Select an inquiry area',description:'Describe the task in 10–5000 characters',format:'This file format is not supported',size:'The file must be no larger than 10 MB',empty:'An empty file cannot be attached',file:'Attachment',remove:'Remove attachment',required:'Required field'}};
const lang=()=>document.documentElement.lang==='en'?'en':'uk',words=()=>dict[lang()];
const ids=['name','email','direction','description'];
function issue(id){const value=(id==='direction'?$('#direction-value').value:$('#'+id).value).trim();if(id==='name')return value.length<2;if(id==='email')return !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)||!$('#email').validity.valid;if(id==='direction')return !options.some(o=>o.dataset.value===value);return value.length<10||value.length>5000}
function validate(id){const bad=issue(id),e=$('#'+id);e.setAttribute('aria-invalid',String(bad));e.dataset.valid=String(!bad);$('#'+id+'-error').textContent=bad?words()[id]:'';return !bad}
function close(focus=false){list.hidden=true;trigger.setAttribute('aria-expanded','false');if(focus)trigger.focus()}
function open(index){if(sending)return;list.hidden=false;trigger.setAttribute('aria-expanded','true');active=index??Math.max(0,options.findIndex(o=>o.dataset.value===$('#direction-value').value));options[active].focus()}
function choose(i){$('#direction-value').value=options[i].dataset.value;options.forEach((o,j)=>o.setAttribute('aria-selected',String(i===j)));close(true);touched.add('direction');validate('direction');render();}
trigger.addEventListener('click',()=>list.hidden?open():close(true));trigger.addEventListener('keydown',e=>{if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();open(e.key==='End'||e.key==='ArrowUp'?options.length-1:0)}});
options.forEach((o,i)=>{o.addEventListener('click',()=>choose(i));o.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();close(true)}else if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();active=e.key==='Home'?0:e.key==='End'?options.length-1:(i+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;options[active].focus()}else if(e.key.length===1&&!e.ctrlKey&&!e.metaKey){const n=options.findIndex(x=>x.textContent.toLowerCase().startsWith(e.key.toLowerCase()));if(n>=0)options[n].focus()}})});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.dropdown'))close()});$('.dropdown').addEventListener('focusout',()=>setTimeout(()=>{if(!$('.dropdown').contains(document.activeElement)){close();touched.add('direction');validate('direction')}},0));
ids.filter(id=>id!=='direction').forEach(id=>{const e=$('#'+id);e.addEventListener('blur',()=>{touched.add(id);validate(id)});e.addEventListener('input',()=>{if(touched.has(id))validate(id);if(state==='success'){state='';render()}})});
$('#upload-button').addEventListener('click',()=>{fileIssue='';render();$('#file').click()});$('#file').addEventListener('change',()=>{const candidate=$('#file').files[0];if(!candidate)return;const ext=candidate.name.split('.').pop().toLowerCase();fileIssue=!['pdf','doc','docx','xls','xlsx','jpg','jpeg','png','zip','step','stp','dwg','dxf'].includes(ext)?'format':candidate.size>10*1024*1024?'size':candidate.size===0?'empty':'';if(!fileIssue)file=candidate;$('#file').value='';render()});$('#remove-file').addEventListener('click',()=>{file=null;fileIssue='';render();$('#upload-button').focus()});
function render(){const w=words(),selected=options.find(o=>o.dataset.value===$('#direction-value').value);$('#direction-text').textContent=selected?selected.textContent:w.placeholder;$('#submit-text').textContent=sending?w.sending:w.submit;$('#file-error').textContent=fileIssue?w[fileIssue]:'';$('#upload-button').setAttribute('aria-invalid',String(!!fileIssue));$('#file').setAttribute('aria-label',w.file);$('#remove-file').setAttribute('aria-label',w.remove);$('#file-summary').hidden=!file;if(file){$('#file-name').textContent=file.name;$('#file-size').textContent=new Intl.NumberFormat(lang(),{maximumFractionDigits:1}).format(file.size>=1048576?file.size/1048576:file.size/1024)+(file.size>=1048576?(lang()==='uk'?' МБ':' MB'):(lang()==='uk'?' КБ':' KB'))}touched.forEach(validate);const status=$('#form-status');status.hidden=!state;status.dataset.state=state;status.textContent=state?w[state]:'';$('#form-fields').disabled=sending;form.setAttribute('aria-busy',String(sending))}
form.addEventListener('submit',async e=>{e.preventDefault();if(sending)return;ids.forEach(id=>touched.add(id));const invalid=ids.filter(id=>!validate(id));if(invalid.length){$('#'+invalid[0]).focus();return}if(fileIssue){$('#upload-button').focus();return}const cfg=window.IFTORA_CONTACT_CONFIG||{};if(!cfg.endpoint){state='unconfigured';render();return}let endpoint;try{endpoint=new URL(cfg.endpoint,location.href);if(endpoint.protocol!=='https:'&&endpoint.origin!==location.origin)throw Error('Invalid endpoint')}catch{state='error';render();return}
const data=new FormData(form);data.delete('attachment');for(const id of ['name','email','description','company','phone'])data.set(id,$('#'+id).value.trim());if(file)data.set('attachment',file,file.name);data.set('language',lang());sending=true;state='sending';render();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),cfg.timeoutMs||20000);try{const response=await fetch(endpoint.href,{method:'POST',body:data,headers:{Accept:'application/json'},signal:controller.signal,credentials:'omit'});if(!response.ok)throw Error('Rejected');const result=await response.json();if(result.ok!==true)throw Error('Unconfirmed');state='success'}catch{state='error'}finally{clearTimeout(timer);sending=false;render();if(state==='success')$('#form-status').focus()}});
new MutationObserver(render).observe(document.documentElement,{attributes:true,attributeFilter:['lang']});render();if(location.hash==='#request-form')requestAnimationFrame(()=>$('#name').focus({preventScroll:true}));
})();
