const dialog=document.querySelector('#menu-dialog'),menu=document.querySelector('#menu');let lang='uk';
menu.onclick=()=>{dialog.showModal();menu.setAttribute('aria-expanded','true');labels()};document.querySelector('#close-menu').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{menu.setAttribute('aria-expanded','false');menu.focus();labels()});dialog.querySelectorAll('a').forEach(a=>a.onclick=()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
const bilingual=[...document.querySelectorAll('[data-en]')];bilingual.forEach(e=>e.dataset.uk=e.textContent);
function labels(){const en=lang==='en';menu.setAttribute('aria-label',dialog.open?(en?'Close menu':'Закрити меню'):(en?'Open menu':'Відкрити меню'));document.querySelector('#close-menu').setAttribute('aria-label',en?'Close menu':'Закрити меню');dialog.setAttribute('aria-label',en?'Navigation':'Навігація');document.querySelectorAll('[data-lang]').forEach(b=>b.setAttribute('aria-label',b.dataset.lang==='uk'?(en?'Ukrainian':'Українська'):(en?'English':'Англійська')));document.querySelector('.skip').textContent=en?'Skip to content':'До змісту';document.querySelector('.language').setAttribute('aria-label',en?'Language':'Мова');document.querySelectorAll('[data-home]').forEach(a=>a.href=new URL('../?lang='+lang,location.href).href);document.querySelectorAll('[data-site-link]').forEach(a=>{const u=new URL(a.href);u.searchParams.set('lang',lang);a.href=u.href})}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>{lang=b.dataset.lang;document.documentElement.lang=lang;bilingual.forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll('[data-lang]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.lang===lang)));document.title=lang==='en'?'IFTORA — Our process':'IFTORA — Як працюємо';const u=new URL(location.href);u.searchParams.set('lang',lang);history.replaceState(null,'',u);labels()});
if(new URLSearchParams(location.search).get('lang')==='en')document.querySelector('[data-lang=en]').click();labels();

const reduced=matchMedia('(prefers-reduced-motion:reduce)'),flow=document.querySelector('.process-flow'),steps=[...document.querySelectorAll('.flow-step')],route=document.querySelector('.flow-route');
let running=false,finished=false;
function drawRoute(){const box=flow.getBoundingClientRect(),mobile=innerWidth<=700;route.setAttribute('viewBox',`0 0 ${box.width} ${box.height}`);route.innerHTML='';let prev=null;steps.forEach((step,i)=>{const r=step.querySelector('svg').getBoundingClientRect(),pt={x:r.x-box.x+r.width/2,y:r.y-box.y+r.height/2};let d;if(!prev)d=`M${pt.x} ${pt.y-40}V${pt.y}`;else if(mobile)d=`M${prev.x} ${prev.y}V${pt.y}`;else if(Math.abs(prev.y-pt.y)<30)d=`M${prev.x} ${prev.y}H${pt.x}`;else d=`M${prev.x} ${prev.y}H${box.width-10}V${pt.y}H${pt.x}`;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',d);path.setAttribute('pathLength','1');path.style.setProperty('--delay',`${i*.85}s`);route.append(path);step.style.setProperty('--delay',`${i*.85+.65}s`);prev=pt});if(finished)flow.classList.add('complete')}
function start(){if(running||finished)return;running=true;flow.classList.add('started');setTimeout(()=>{finished=true;flow.classList.add('complete')},4900)}
if(reduced.matches){finished=true;flow.classList.add('complete')}else{flow.classList.add('motion-ready');const obs=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){start();obs.disconnect()}},{threshold:.12});obs.observe(flow)}
new ResizeObserver(drawRoute).observe(flow);document.fonts.ready.then(drawRoute);reduced.addEventListener('change',()=>{if(reduced.matches){finished=true;flow.classList.add('complete')}});

// Mobile stages reveal independently, once, as each enters the viewport.
const mobileLayout=matchMedia('(max-width:700px)');
const seenMobile=new WeakSet();
const stageObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;const step=entry.target;seenMobile.add(step);step.classList.add('mobile-shown');stageObserver.unobserve(step)}),{threshold:.25});
function mobileStages(){stageObserver.disconnect();steps.forEach(step=>{step.classList.remove('mobile-pending','mobile-shown');if(!mobileLayout.matches||reduced.matches)return;if(seenMobile.has(step))return;step.classList.add('mobile-pending');stageObserver.observe(step)})}
mobileStages();mobileLayout.addEventListener('change',mobileStages);reduced.addEventListener('change',mobileStages);

function contactLinks(){const language=document.documentElement.lang;document.querySelectorAll('[data-contact-form]').forEach(a=>a.href='../contacts/?lang='+language+'#request-form');document.querySelectorAll('[data-contact-page]').forEach(a=>a.href='../contacts/?lang='+language)}contactLinks();document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',contactLinks));
